# Generated by Django 2.2.7 on 2021-02-13 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210213_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='urls',
        ),
    ]
