# Generated by Django 2.2.7 on 2021-02-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20210213_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='urls',
            field=models.TextField(max_length=500),
        ),
    ]
