# Generated by Django 2.2.7 on 2021-02-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20210213_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='urls',
            field=models.URLField(),
        ),
    ]
